# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'InfinitiWould' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for InfinitiWould
  pod 'RealmSwift', '~> 4.4.0'
  pod 'Alamofire', '~> 5.2'
  pod 'NVActivityIndicatorView'
  pod 'GoogleMaps', '5.0.0'
  pod 'GooglePlaces', '5.0.0'
end
